export type { Vendor, CreateVendorDto, UpdateVendorDto } from './vendor';
export type { Customer, Vehicle, CreateCustomerDto, UpdateCustomerDto } from './customer';
export type { Product, CreateProductDto, UpdateProductDto, GlassPosition } from './product';
export type { Job, CreateJobDto, UpdateJobDto, PaymentType, DamageType } from './job';
export type { Claim, CreateClaimDto, UpdateClaimDto, ClaimTimelineStep, Insurer } from './claim';
export type { Invoice, CreateInvoiceDto, UpdateInvoiceDto, InvoiceLineItem } from './invoice';
export type { DashboardData, DashboardKpi, DashboardRecentCustomer, DashboardPendingClaim, DashboardRecentJob } from './dashboard';
export type { Branch, BranchCreatePayload, BranchUpdatePayload, BranchStatus } from './branch';
export type { AppUser, AppRole, UserStatus, InvitationStatus, UserCreatePayload, StaffCreatePayload, StaffUpdatePayload, BackendStaffRole } from './appUser';
export type { BranchPerformanceRow, AdminSummary } from './adminSummary';
export type { InsuranceRule, InsuranceRulePayload, InsuranceRuleUpdatePayload, BoardType, CCCondition } from './insuranceRule';
export type { VehicleModel, VehicleModelPayload, VehicleModelUpdatePayload } from './vehicleModel';
export { BRANDS, BRAND_MODEL_MAP } from './vehicleModel';
